---
#
# This file runs only when the access point is enabled
#

# We have to uninstall and then reinstall to make sure that we can
# switch between Adafruit's custom one and the operating systems default
- name: Uninstall hostapd if present
  apt: name=hostapd purge=true state=absent

- name: Remove custom hostapd (if it exists)
  file: path=/usr/sbin/hostapd state=absent

- name: Uninstall hostapd
  apt: name=hostapd purge=true state=absent
  when: router_access_point_nic == false

- name: Install hostapd
  apt: name=hostapd
  when: router_access_point_nic != false

- name: Install custom hostapd
  shell: "{{ item }}"
  with_items:
    - wget http://adafruit-download.s3.amazonaws.com/adafruit_hostapd_14128.zip
    - unzip adafruit_hostapd_14128.zip
    - chown root.root hostapd
    - chmod +x hostapd
    - mv hostapd /usr/sbin/hostapd
    - rm adafruit_hostapd_14128.zip
  when: use_adafruit_hostapd == true

- name: Configure hostapd defaults
  template:
    src: etc/default/hostapd.j2
    dest: /etc/default/hostapd
  when: router_access_point_nic != false

- name: Configure hostapd
  template:
    src: etc/hostapd/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
  notify:
    - Restart hostapd
  when: router_access_point_nic != false

- name: Remove hostapd configuration
  file: path="{{ item }}" state=absent
  with_items:
    - "/etc/hostapd/hostapd.conf"
    - "/etc/default/hostapd"
  when: router_access_point_nic == false
