---

- name: Enable IPv4 forwarding
  lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_forward=1"

#
# Configure network devices
#
- name: Install main network interfaces file
  template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces

- name: Install internal network interface file
  template:
    src: etc/network/interfaces.d/internal.j2
    dest: /etc/network/interfaces.d/internal

- name: Install external network interface file
  template:
    src: etc/network/interfaces.d/external.j2
    dest: /etc/network/interfaces.d/external

- name: Install wireless network interface file
  template:
    src: etc/network/interfaces.d/wireless.j2
    dest: /etc/network/interfaces.d/wireless
  when: router_access_point_nic != false
- name: Remove wireless network interface file
  file:
    path: /etc/network/interfaces.d/wireless
    state: absent
  when: router_access_point_nic == false

#
# Configure routing and firewall
#
- name: Install IP Tables rules
  template:
    src: etc/iptables.rules.j2
    dest: /etc/iptables.rules

- name: Make iptables rules apply automatically
  template:
    src: etc/network/if-up.d/iptables-restore.j2
    dest: /etc/network/if-up.d/iptables-restore

- name: Fix iptables rules permissions
  file:
    mode: 0755
    path: /etc/network/if-up.d/iptables-restore

#
# DHCP
#
- name: Configure DHCPD
  template:
    src: etc/dhcp/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: Configure DHCP server
  template:
    src: "etc/default/isc-dhcp-server.j2"
    dest: "/etc/default/isc-dhcp-server"

- name: Add DHCP host information
  with_items: "{{ internal_hosts }}"
  lineinfile:
    dest: /etc/dhcp/dhcpd.conf
    state: present
    line: "host {{ item.name }} { hardware ethernet {{ item.mac }}; fixed-address {{ internal_ip_octet_1 }}.{{ internal_ip_octet_2 }}.{{ internal_ip_octet_3 }}.{{ item.ip }}; }"
  notify: Restart DHCPD

#
# Miscellaneous
#
- name: Setup ddclient
  template:
    src: etc/ddclient.conf.j2
    dest: /etc/ddclient.conf
  notify: Restart ddclient
  when: ddclient_hostname is defined

- name: Make sure ddclient configuration is only readable by root
  file: mode=0700 dest="/etc/ddclient.conf"
  when: ddclient_hostname is defined

- name: Remove ddclient configuration
  file: dest="/etc/ddclient.conf" state=absent
  notify: Stop ddclient
  when: ddclient_hostname is undefined

#
# Apache configuration
#
- name: Configure web server
  template:
    src: etc/apache2/sites-available/router.conf.j2
    dest: /etc/apache2/sites-available/router.conf

- name: Enable router Apache config
  shell: "a2ensite router"
  notify: "Restart Apache"
  when: router_web_ui

- name: Disable router Apache config
  shell: "a2dissite router"
  notify: "Restart Apache"
  when: not router_web_ui
