---

- import_tasks: "software.yml"
  become: yes
  become_user: root

- import_tasks: "configure.yml"
  become: yes
  become_user: root

- import_tasks: "access-point.yml"
  become: yes
  become_user: root

- import_tasks: "vpn.yml"
  become: yes
  become_user: root
  when: vpn_enabled == true
