---
- name: Install DHCPD
  sudo: yes
  apt: name=isc-dhcp-server

- name: Install Bridge Utils
  apt: name=bridge-utils

- name: Install ddclient
  apt: name=ddclient

- name: Install SSHFS
  apt: name=sshfs

#
# MINIUPNPD didn't even working out... make sure there's no trace
#
- name: Uninstall UPnP daemon
  apt: name="{{ item }}" state=absent
  with_items:
    - miniupnpc
    - miniupnpd

- name: Remove UPnP daemon configuration
  file:
    path: /etc/default/miniupnpd
    state: absent
