---
#
# OpenVPN configuration. Shout out to
# https://readwrite.com/2014/04/10/raspberry-pi-vpn-tutorial-server-secure-web-browsing/
# for making a ridiculously easy to follow tutorial. I, however, disagree
# with him that 2048 bits is paranoid. I also object to using TripleDES
# for setting up clients. TripleDES is so weak that it's basically plaintext
# for the NSA.
#

- name: Install OpenVPN
  apt: name=openvpn state=present

- name: Configure OpenVPN
  template:
    src: etc/openvpn/server.conf.j2
    dest: /etc/openvpn/server.conf

#
# EasyRSA configuration
#
- name: Copy Easy RSA into place
  command: rsync -a /usr/share/easy-rsa/ /etc/openvpn/easy-rsa/
  args:
    creates: /etc/openvpn/easy-rsa/build-ca

- name: Install Easy RSA variables
  template:
    src: etc/openvpn/easy-rsa/vars.j2
    dest: /etc/openvpn/easy-rsa/vars

- name: Install Easy RSA OpenSSL configuration
  template:
    src: etc/openvpn/easy-rsa/openssl.cnf.j2
    dest: /etc/openvpn/easy-rsa/openssl.cnf

- name: Lock down Easy RSA
  file:
    path: /etc/openvpn/easy-rsa/
    state: directory
    mode: 0700

- name: Create keys directory
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
    mode: 0700

- name: Create keys index
  file:
    path: /etc/openvpn/easy-rsa/keys/index.txt
    state: present
    mode: 0600

- name: Disable unique key checks
  lineinfile:
    path: /etc/openvpn/easy-rsa/keys/index.txt.attr
    regexp: '^unique_subject.*'
    line: 'unique_subject = no'
    state: present
    create: yes

- name: Create keys serial if necessary
  shell: echo 01 > /etc/openvpn/easy-rsa/keys/serial
  args:
    creates: /etc/openvpn/easy-rsa/keys/serial

#
# Initialize certificates
#
- name: Initialize certificate authority
  shell: ". ./vars && ./pkitool --initca"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/ca.key

- name: Build key server
  shell: ". ./vars && ./pkitool --server {{ vpn_host }}"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/router.key

- name: Build Diffie-Hellman key exchange data
  shell: ". ./vars && ./build-dh"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/dh2048.pem

- name: Generate hash-based message authentication code (HMAC)
  shell: "openvpn --genkey --secret keys/ta.key"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/keys/ta.key

#
# Client setup
#
- name: Generate and sign client keys
  shell: ". ./vars && ./pkitool {{ item }} && ./pkitool --sign {{ item }}"
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: "/etc/openvpn/easy-rsa/keys/{{ item }}.crt"
  with_items: "{{ vpn_clients }}"
  when: vpn_clients
