---

- name: "Restart hostapd"
  become: yes
  become_user: root
  service: state=restarted name=hostapd

- name: "Restart DHCPD"
  become: yes
  become_user: root
  service: state=restarted name=isc-dhcp-server

- name: "Restart ddclient"
  become: yes
  become_user: root
  service: state=restarted name=ddclient
- name: "Stop ddclient"
  become: yes
  become_user: root
  service: state=stopped name=ddclient

- name: "Restart Apache"
  become: yes
  become_user: root
  service: state=restarted name=apache2
